config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :sessions, only: [:create]
    resources :dashboards
    resources :editusers
    resources :homes

    get 'login', to: 'sessions#new'
    get 'logout', to: 'sessions#destroy'

    root 'dashboards#index'
  end

  resources :dashboards
  resources :users, only: [:new, :create]
  resources :sessions, only: [:create]
  resources :homes
  resources :sends
  resources :success, only:[:index]

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  root 'dashboards#index'
end

app/models/admin/dashboard.rb
class Admin::Dashboard < ApplicationRecord
	validates :detail, presence: true
	belongs_to :user
end

app/models/admin/home.rb
class Admin::Home < ApplicationRecord
	validates :detail, presence: true
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord
	has_secure_password

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :phone_no, uniqueness: true, presence: true
	validates :email, uniqueness: true, presence: true

	has_many :dashboards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
	validates :detail, presence: true
	belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
	validates :detail, presence: true
end

app/models/send.rb
class Send < ApplicationRecord
	validates :recipient_email, presence: true
	validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :phone_no, uniqueness: true, presence: true
	validates :email, uniqueness: true, presence: true

	has_many :dashboards
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_admin_user, only: %i[ show edit update destroy ]

  def index
    @pagy, @admin_user = pagy(Admin::User.all.order('created_at ASC'), items: 3)
  end

  def new
    @admin_user = Admin::User.new
  end

  def create
    @admin_user = Admin::User.new(admin_user_params)

    if @admin_user.save
      session[:admin_user_id] = @admin_user.id
      flash[:success] =  'You have successfully created new user'
      redirect_to '/admin/users'
    else
      render :new
    end
  end

  def update
    @admin_user = Admin::User.find(params[:id])
    @admin_user.update(params.require(:admin_user).permit(:first_name, :last_name, :phone_no, :email, :balance, :admin))
    flash[:success] =  'User Successfully Updated!'
    redirect_to '/admin/users'
  end

  def destroy
    @admin_user = Admin::User.find(params[:id])
    if (admin_current_user == @admin_user) && (@admin_user.admin == true)
      flash[:error] = "You can't delete admin or own account!"
      redirect_to '/admin/users'
    else
      @admin_user.destroy
      flash[:success] =  'User Successfully Deleted!'
      redirect_to '/admin/users'
    end
  end

  private
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    def admin_user_params
      params.require(:admin_user).permit(:first_name, :last_name, :phone_no, :email, :balance, :admin, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include ApplicationHelper
  
	protect_from_forgery with: :exception
  before_action :require_valid_user!

  def current_user
    if !session[:user_id].blank?
      @user ||= User.find(session[:user_id])
    end
  end

  def require_valid_user!
    if current_user.nil?
      flash[:error] = 'You must be logged in to access that page!'
      redirect_to '/homes'
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @dashboards = @user.dashboards.all if @user

    @pagy, @dashboards = pagy(Dashboard.all.order('created_at ASC'), items: 4)

    @homes = Home.all
    @users = User.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_valid_user!
  before_action :reset_session

  def index
    @home = Home.all
  end

  # def new
  #   @home = Home.new
  # end

  # def create
  #   @home = Home.new(home_params)

  #   respond_to do |format|
  #     if @home.save
  #       format.html { redirect_to @home, notice: "Home was successfully created." }
  #       format.json { render :show, status: :created, location: @home }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @home.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def update
  #   respond_to do |format|
  #     if @home.update(home_params)
  #       format.html { redirect_to @home, notice: "Home was successfully updated." }
  #       format.json { render :show, status: :ok, location: @home }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @home.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @home.destroy
  #   respond_to do |format|
  #     format.html { redirect_to '/home', notice: "Home was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   def set_home
  #     @home = Home.find(params[:id])
  #   end

  #   def home_params
  #     params.require(:home).permit(:detail)
  #   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_valid_user!
  before_action :reset_session

  def index
    @homes = Home.all
  end
end

app/controllers/sends_controller.rb
class SendsController < ApplicationController
  def index
    @sends = Send.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_valid_user!, except: [:destroy]

  def new
  end

  def create
    reset_session
    @user = User.find_by(email: session_params[:email])

    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Welcome back!'
      redirect_to root_path
    else
      flash[:error] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/success_controller.rb
class SuccessController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_valid_user!
  before_action :reset_session

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] =  'You have successfully created an account!'
      redirect_to root_path
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_no, :email, :balance, :admin, :password, :password_confirmation)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
	def current_user
    @user ||= User.find(session[:user_id])
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sends_helper.rb
module SendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/userdashboards_helper.rb
module UserdashboardsHelper
	def current_user
    @user ||= User.find(session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<section class="section-margin--small">
  <div class="container" style="background-color: #dfe1fc;padding: 30px;">
    <div class="row">

      <div class="col-md-4 col-lg-3 mb-4 mb-md-0">

        <h5>Edit User Details</h5>
        <h5 style="font-size: 15px;">
          <a href="/admin/users"><i class="fa fa-arrow-left"></i> Go Back</a>
        </h5>

        <% if @admin_user.errors.any? %>
          <div class='alert alert-danger'>
            <p>Please correct the following errors:</p>
            <ul>
              <% @admin_user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

      </div>

      <div class="col-md-6 col-lg-5">

        <%= form_for @admin_user, url: {action: "update"} do |f| %>
          <div class='form-group'>
            <%= f.text_field :first_name, class: 'form-control', value: @admin_user.first_name %>
          </div>
          <div class='form-group'>
            <%= f.text_field :last_name, class: 'form-control', value: @admin_user.last_name %>
          </div>
          <div class='form-group'>
            <%= f.text_field :phone_no, class: 'form-control', value: @admin_user.phone_no %>
          </div>
          <div class='form-group'>
            <%= f.email_field :email, class: 'form-control', value: @admin_user.email %>
          </div>
          <div class='form-group'>
            <%= f.text_field :balance, class: 'form-control', value: @admin_user.balance %>
          </div>
          <div class='form-group' style="padding-top:20px;padding-bottom:20px;">
            <%= f.check_box :admin  %> Admin?
          </div>
          
          <%= f.submit 'Update!', class: 'btn btn-primary' %>
        <% end %>

      </div>

    </div>
  </div>
</section>

app/views/admin/users/index.html.erb
<div id="content" class="py-4">
  <div class="container">
    <div class="row">         

      <div class="col-lg-12"> 

        <!-- Users =============================== -->
        <div class="bg-white shadow-sm rounded py-4 mb-4">
          <h3 class="text-5 font-weight-400 d-flex align-items-center px-4 mb-4">Registered Users</h3>

          <% if flash[:success] %>
            <div class='alert alert-success'><%= flash[:success] %></div>
          <% end %>
          
          <% if flash[:error] %>
            <div class='alert alert-danger'><%= flash[:error] %></div>
          <% end %>

          <!-- Title ======================== -->
          <div style="padding-left: 20px;">
            <a href="/admin/#userid"><i class="fa fa-arrow-left"></i> Go Back</a>
          </div>
          <div class="font-weight-00" style="text-align: right;padding-right:25px;">
            <a href="/admin/users/new"><i class="fas fa-plus" style="padding-bottom: 20px;"> Add New User</i></a>
          </div>

          <!-- Title ======================== -->
          <div class="transaction-title py-2 px-4">
            <div class="row font-weight-00">
              <div style="border-right: 2px solid #a1a3fe;padding-right: 10px;">ID</div>
              <div class="col col-sm-1 text-center" style="border-right: 2px solid #a1a3fe;padding-right: 40px;">Name</div>
              <div class="col col-sm-4 text-center" style="border-right: 2px solid #a1a3fe;">Number</div>
              <div class="col col-sm-3 text-center d-none d-md-block d-lg-block d-xl-block" style="border-right: 2px solid #a1a3fe;">Email</div>
              <div class="col col-sm-2 text-right" style="border-right: 2px solid #a1a3fe;">Edit</div>
              <div class="col col-sm-1 text-center">Delete</div>
            </div>
          </div>
          <!-- Title End --> 
          
          <!-- Info List ===================== -->
          <div class="transaction-list">
            <div class="px-4 py-3">
              <% @admin_user.each do |admin_user| %>
                <div class="row align-items-center flex-row" style="border-bottom: 2px dotted #a1a3fe;padding-bottom: 10px;padding-top: 10px;">

                  <div> 
                    <span class="d-block text-4"><%= admin_user.id %>.</span> 
                  </div>

                  <div class="col col-sm-1 text-center"> 
                    <span class="d-block text-4 font-weight-300">
                      <%= admin_user.first_name %>
                    </span>
                    <span class="d-block text-1 font-weight-300 text-uppercase">
                      <%= admin_user.last_name %>
                    </span> 
                  </div>

                  <div class="col col-sm-4 text-center"> 
                    <span class="d-block text-4"><%= admin_user.phone_no %></span> 
                    <span class="text-muted">Ksh <%= admin_user.balance %></span> 
                  </div>

                  <div class="col col-sm-3 text-center d-none d-md-block d-lg-block d-xl-block"> 
                    <span class="d-block text-4"><%= admin_user.email %></span> 
                    <span class="text-muted">Admin? <%= admin_user.admin %></span> 
                  </div>
                  
                  <div class="col col-sm-2 text-right text-4"> 
                    <span class="text-nowrap">
                      <%= link_to '', edit_admin_user_path(admin_user), :class => "fas fa-edit" %>
                    </span> 
                  </div>

                  <div class="col col-sm-1 text-center text-4"> 
                    <span class="text-nowrap">
                      <%= link_to '', admin_user_path(admin_user), :class => "fas fa-trash", method: :delete, data: {confirm: 'Are you sure?'} %>
                    </span> 
                  </div>

                </div>
              <% end %>
            </div>
          </div>
          <!-- Info List End --> 
        </div>
        <!-- Users End -->

        <i><%= pagy_bootstrap_nav(@pagy).html_safe %></i>

      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<section class="section-margin--small">
  <div class="container" style="background-color: #dfe1fc;padding: 30px;">
    <div class="row">

      <div class="col-md-4 col-lg-3 mb-4 mb-md-0">

        <h1>Sign Up</h1>
        <p>Create a new admin account.  All fields are required.</p>

        <% if @admin_user.errors.any? %>
          <div class='alert alert-danger'>
            <p>Please correct the following errors:</p>
            <ul>
              <% @admin_user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p >
          Already have an account? <%= link_to 'Click here to sign in.', admin_login_path %>
        </p>

      </div>

      <div class="col-md-6 col-lg-5">

        <%= form_for @admin_user do |f| %>
          <div class='form-group'>
            <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
          </div>
          <div class='form-group'>
            <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
          </div>
          <div class='form-group'>
            <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
          </div>
          <div class='form-group'>
            <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
          </div>
          <div class='form-group'>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password' %>
          </div>
          <%= f.submit 'Register', class: 'btn btn-primary' %>
        <% end %>

      </div>

    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="section-margin--small">
  <div class="container" style="background-color: #dfe1fc;padding: 30px;">
    <div class="row">

      <div class="col-md-4 col-lg-3 mb-4 mb-md-0">

        <h1>Sign Up</h1>
        <p>Create a new account.  All fields are required.</p>

        <% if @user.errors.any? %>
          <div class='alert alert-danger'>
            <p>Please correct the following errors:</p>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p >
          Already have an account? <%= link_to 'Click here to sign in.', login_path %>
        </p>

      </div>

      <div class="col-md-6 col-lg-5">

        <%= form_for @user do |f| %>
          <div class='form-group'>
            <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
          </div>
          <div class='form-group'>
            <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
          </div>
          <div class='form-group'>
            <%= f.text_field :phone_no, class: 'form-control', placeholder: 'Phone Number' %>
          </div>
          <div class='form-group'>
            <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
          </div>
          <div class='form-group'>
            <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
          </div>
          <div class='form-group'>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password' %>
          </div>
          <%= f.submit 'Register', class: 'btn btn-primary' %>
        <% end %>

      </div>

    </div>
  </div>
</section>